name: Docker Image CI

on:
  push:
    branches: 
      - "main"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
          cache: maven
          
      - name: Build Application .jar
        working-directory: ./
        run: mvn clean package

      - name: Docker Compose Build
        working-directory: ./
        run: docker compose build

      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USER_NAME }}/curso-springboot-udemy:latest ${{ secrets.DOCKER_USER_NAME }}/curso-springboot-udemy:${{ github.run_id }}
        
          docker push ${{ secrets.DOCKER_USER_NAME }}/curso-springboot-udemy:latest
          docker push ${{ secrets.DOCKER_USER_NAME }}/curso-springboot-udemy:${{ github.run_id }}  
